feat:add common api for etcd v2
php-casbin/etcd-adapter pull request #3
Opened 2022-07-27 14:41 UTC by M1serry

2022-07-27 15:10 UTC, leeqvip requested changes

2022-07-27 15:10 UTC, leeqvip commented on README.md
> +[![License](https://poser.pugx.org/casbin/database-adapter/license)](https://packagist.org/packages/casbin/database-adapter)
Please modify the project name

2022-08-01 05:22 UTC, hsluoyz commented
@M1serry

2022-08-07 15:17 UTC, leeqvip approved these changes

2022-08-07 15:17 UTC, merged

2022-08-07 15:19 UTC, leeqvip commented
@M1serry Next, complete Github Actions to run unit tests and automate releases.